version: '3.8'

services:
  example:
    build:
      dockerfile: Dockerfile # докер файл
    container_name: front # имя контейнера
    image: example # Образ докер
    restart: unless-stopped # перезагрузка по любым случаям, кроме остановки контейнера.
    ports:
      - "0.0.0.0:80:80" # 80 порт приложения, 80 внешний порт докера, на локальный адресс устройства запуска.